[tasks.outdated]
args = ["outdated", "--root-deps-only", "--exit-code", "0"]

[tasks.ci]
workspace = false
run_task = { name = "ci-flow", fork = true }

[tasks.readme]
workspace = false
command = "cargo"
args = ["readme", "--output", "README.md"]

[tasks.t]
workspace = false
run_task = { name = "test", fork = true }

[tasks.r]
workspace = false
run_task = "readme"
